---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarrnew
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /home/gandalf/sonarrnew:/config
      - /home/gandalf/win2/TV2:/tv
      - /media/win5/TV:/tv2
      - /media/win3/TV:/tv3
      - /home/gandalf/win2:/downloads
    ports:
      - 9292:9292
    restart: unless-stopped
